spring:
  application:
    name: gamevault

  config:
    import: optional:file:.env[.properties]

  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/gamevault
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false

  flyway:
    enabled: true
    locations: classpath:db/migration

  rawg:
    api-key: ${RAWG_API_KEY:}